import { mkdirSync } from 'node:fs';
import { rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { listAllDemos, type DemoRow } from './db';

const OUTPUT_PATH = process.env.PORTAL_TRAEFIK_FILE ?? '/traefik-dynamic/portal-managed.yml';
const PORTAL_HOST = process.env.PORTAL_HOST ?? 'demo.almostimpossible.agency';
const PORTAL_COOLIFY_APP_ID = process.env.PORTAL_COOLIFY_APP_ID ?? '';
const CERT_RESOLVER = process.env.PORTAL_CERT_RESOLVER ?? 'letsencrypt-wildcard';
const TAILSCALE_CGNAT = '100.64.0.0/10';

const PRIORITY_GATED_DEMO = 1000;
const PRIORITY_ADMIN_ALLOWLIST = 2000;

type Block = string;

export function renderTraefikYaml(rows: DemoRow[]): string {
  const gated = rows.filter(
    (r) => r.password_gated === 1 && r.password_hash && r.coolify_app_id && r.archived === 0,
  );

  const blocks: Block[] = ['# Generated by agency-demo-portal. Do not hand-edit.', 'http:'];

  blocks.push('  middlewares:');
  blocks.push('    tailscale-only:');
  blocks.push('      ipAllowList:');
  blocks.push('        sourceRange:');
  blocks.push(`          - ${TAILSCALE_CGNAT}`);
  blocks.push('          - 127.0.0.1/32');

  for (const r of gated) {
    blocks.push(`    demo-${r.slug}-basicauth:`);
    blocks.push('      basicAuth:');
    blocks.push('        users:');
    blocks.push(`          - ${yamlString(`${r.basic_auth_user}:${r.password_hash}`)}`);
  }

  blocks.push('  routers:');

  if (PORTAL_COOLIFY_APP_ID) {
    blocks.push('    portal-admin-allowlist:');
    blocks.push(`      rule: ${yamlString(`Host(\`${PORTAL_HOST}\`) && PathPrefix(\`/admin\`)`)}`);
    blocks.push(`      priority: ${PRIORITY_ADMIN_ALLOWLIST}`);
    blocks.push('      entryPoints: [https]');
    blocks.push(`      service: ${yamlString(`https-0-${PORTAL_COOLIFY_APP_ID}@docker`)}`);
    blocks.push('      tls:');
    blocks.push(`        certResolver: ${CERT_RESOLVER}`);
    blocks.push('      middlewares:');
    blocks.push('        - tailscale-only');
  }

  for (const r of gated) {
    blocks.push(`    portal-${r.slug}:`);
    blocks.push(`      rule: ${yamlString(`Host(\`${r.slug}.demo.almostimpossible.agency\`)`)}`);
    blocks.push(`      priority: ${PRIORITY_GATED_DEMO}`);
    blocks.push('      entryPoints: [https]');
    blocks.push(`      service: ${yamlString(`https-0-${r.coolify_app_id}@docker`)}`);
    blocks.push('      tls:');
    blocks.push(`        certResolver: ${CERT_RESOLVER}`);
    blocks.push('      middlewares:');
    blocks.push(`        - demo-${r.slug}-basicauth`);
  }

  return blocks.join('\n') + '\n';
}

export async function writeTraefikConfig(): Promise<string> {
  const rows = listAllDemos();
  const yaml = renderTraefikYaml(rows);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });

  const tmpPath = join(dirname(OUTPUT_PATH), `.portal-managed.${process.pid}.tmp`);
  await writeFile(tmpPath, yaml, { mode: 0o644 });
  await rename(tmpPath, OUTPUT_PATH);

  return OUTPUT_PATH;
}

function yamlString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
