import { mkdirSync } from 'node:fs';
import { rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { listAllDemos, type DemoRow } from './db';

const OUTPUT_PATH = process.env.PORTAL_TRAEFIK_FILE ?? '/traefik-dynamic/portal-managed.yml';
const CERT_RESOLVER = process.env.PORTAL_CERT_RESOLVER ?? 'letsencrypt-wildcard';

const PRIORITY_GATED_DEMO = 1000;

type Block = string;

// Renders per-demo basicAuth middleware + parallel routers for password-gated demos.
// The /admin IP-allowlist (tailscale-only middleware + router) lives in operator-edited
// inbound-stack.yml so it's active from the first portal deploy, not bootstrapped by the
// portal itself. See demo-portal-v1-build memory for the operator hand-edit.
export function renderTraefikYaml(rows: DemoRow[]): string {
  const gated = rows.filter(
    (r) => r.password_gated === 1 && r.password_hash && r.coolify_app_id && r.archived === 0,
  );

  const blocks: Block[] = ['# Generated by agency-demo-portal. Do not hand-edit.', 'http:'];

  if (gated.length === 0) {
    blocks.push('  middlewares: {}');
    blocks.push('  routers: {}');
    return blocks.join('\n') + '\n';
  }

  blocks.push('  middlewares:');
  for (const r of gated) {
    blocks.push(`    demo-${r.slug}-basicauth:`);
    blocks.push('      basicAuth:');
    blocks.push('        users:');
    blocks.push(`          - ${yamlString(`${r.basic_auth_user}:${r.password_hash}`)}`);
  }

  blocks.push('  routers:');
  for (const r of gated) {
    blocks.push(`    portal-${r.slug}:`);
    blocks.push(`      rule: ${yamlString(`Host(\`${r.slug}.demo.almostimpossible.agency\`)`)}`);
    blocks.push(`      priority: ${PRIORITY_GATED_DEMO}`);
    blocks.push('      entryPoints: [https]');
    blocks.push(`      service: ${yamlString(`https-0-${r.coolify_app_id}@docker`)}`);
    blocks.push('      tls:');
    blocks.push(`        certResolver: ${CERT_RESOLVER}`);
    blocks.push('      middlewares:');
    blocks.push(`        - demo-${r.slug}-basicauth`);
  }

  return blocks.join('\n') + '\n';
}

export async function writeTraefikConfig(): Promise<string> {
  const rows = listAllDemos();
  const yaml = renderTraefikYaml(rows);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });

  const tmpPath = join(dirname(OUTPUT_PATH), `.portal-managed.${process.pid}.tmp`);
  await writeFile(tmpPath, yaml, { mode: 0o644 });
  await rename(tmpPath, OUTPUT_PATH);

  return OUTPUT_PATH;
}

function yamlString(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
